### PR TITLE
feat: add IMAP ID extension (RFC 2971) support

### PR DESCRIPTION
**Pull request by nuffin**
use imaplib2 to support RFC 2971, the IMAP ID extension

### CODE REVIEW

**Comment by rpuntaie** [comment]
I think it is not a good idea to support RFC 2971's (ID).
Servers could decide not to serve some clients.

`getmail` is just a wrapper around cpython's `imaplib.py`.
It is like someone's private script to retrieve their e-mail.

A comparison shows that `imaplib2` is quite different from cpython's `imaplib.py`.
I don't want to analyze the differences.
imaplib2 could make changes in the future and add a burden on getmail.
Those who want RFC 2971 can add support themselves and give it their chosen ID.

I found:
https://github.com/python/cpython/issues/98092

**Comment by nuffin** [comment]
I have no problem with that.

However, I have found that some service providers have IMAP servers that require the client to send an ID command before the service will be provided.  I don't know why they do this, maybe for data collecting and analyzing (to calculate the percentage of each client, anyway), but the users can not use getmail6 to check emails.  This patch gives the users of these providers the possibility to use getmail6.

I forked and add modified as this patch, and then add a comment in the README.md of my master branch.

**Comment by nuffin** [comment]
There is a clause stating in RFC2971 in [`3 . Specification`](https://www.rfc-editor.org/rfc/rfc2971#section-3) section

```
      Servers MUST NOT deny access to or refuse service for a client
      based on information from the ID command.  Clients MUST NOT refuse
      to operate or limit their operation with a server based on the ID
      response.
```

I would expect all servers to adhere to this clause. 😆

**Comment by rpuntaie** [comment]
I merged #189.

**Comment by nuffin** [comment]
> I merged #189.

OK, I think that should be better.

**Pull request closed without merging**
